// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/typed/sealedsecrets/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBitnamiV1alpha1 struct {
	*testing.Fake
}

func (c *FakeBitnamiV1alpha1) SealedSecrets(namespace string) v1alpha1.SealedSecretInterface {
	return &FakeSealedSecrets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBitnamiV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
