// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/apis/sealedsecrets/v1alpha1"
	sealedsecretsv1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/typed/sealedsecrets/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSealedSecrets implements SealedSecretInterface
type fakeSealedSecrets struct {
	*gentype.FakeClientWithList[*v1alpha1.SealedSecret, *v1alpha1.SealedSecretList]
	Fake *FakeBitnamiV1alpha1
}

func newFakeSealedSecrets(fake *FakeBitnamiV1alpha1, namespace string) sealedsecretsv1alpha1.SealedSecretInterface {
	return &fakeSealedSecrets{
		gentype.NewFakeClientWithList[*v1alpha1.SealedSecret, *v1alpha1.SealedSecretList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("sealedsecrets"),
			v1alpha1.SchemeGroupVersion.WithKind("SealedSecret"),
			func() *v1alpha1.SealedSecret { return &v1alpha1.SealedSecret{} },
			func() *v1alpha1.SealedSecretList { return &v1alpha1.SealedSecretList{} },
			func(dst, src *v1alpha1.SealedSecretList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SealedSecretList) []*v1alpha1.SealedSecret {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SealedSecretList, items []*v1alpha1.SealedSecret) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
