// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissealedsecretsv1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/apis/sealedsecrets/v1alpha1"
	versioned "github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bitnami-labs/sealed-secrets/pkg/client/informers/externalversions/internalinterfaces"
	sealedsecretsv1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/client/listers/sealedsecrets/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SealedSecretInformer provides access to a shared informer and lister for
// SealedSecrets.
type SealedSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() sealedsecretsv1alpha1.SealedSecretLister
}

type sealedSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSealedSecretInformer constructs a new informer for SealedSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSealedSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSealedSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSealedSecretInformer constructs a new informer for SealedSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSealedSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BitnamiV1alpha1().SealedSecrets(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BitnamiV1alpha1().SealedSecrets(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BitnamiV1alpha1().SealedSecrets(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BitnamiV1alpha1().SealedSecrets(namespace).Watch(ctx, options)
			},
		}, client),
		&apissealedsecretsv1alpha1.SealedSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *sealedSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSealedSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sealedSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissealedsecretsv1alpha1.SealedSecret{}, f.defaultInformer)
}

func (f *sealedSecretInformer) Lister() sealedsecretsv1alpha1.SealedSecretLister {
	return sealedsecretsv1alpha1.NewSealedSecretLister(f.Informer().GetIndexer())
}
