--- 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example
spec:
  encryptedData:
    server1: "AgA+dujiBo..."
    server2: "AgCC4/FvhZ..."
    database1: "AgBtYQzl3T..."
  template:
    metadata:
      creationTimestamp: null
      name: example
      namespace: default
    data:
      myconfig.json: |
        {
               "Server": [{
                               "host": "foobar",
                               "ip": "10.10.10.12",
                               "port": "22",
                               "env": "SOME_ENV",
                               "user": "myuser",
                               "password": {{ toJson .server1 }},
                               "role": "foo"
                       },{
                               "host": "barfoo",
                               "ip": "10.10.10.11",
                               "port": "22",
                               "env": "SOME_OTHER_STUFF",
                               "user": "otheruser",
                               "password": {{ toJson .server2 }},
                               "role": "foo"
                       }
               ],
               "Database": [{
                               "host": "somedb",
                               "ip": "10.10.10.10",
                               "port": "1521",
                               "sid": "FOO",
                               "env": "BAZ",
                               "user": "abcdefg123",
                               "password": {{ toJson .database1 }},
                               "role": "foo"
                       }
               ]
        }
