// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SealedSecretListerExpansion allows custom methods to be added to
// SealedSecretLister.
type SealedSecretListerExpansion interface{}

// SealedSecretNamespaceListerExpansion allows custom methods to be added to
// SealedSecretNamespaceLister.
type SealedSecretNamespaceListerExpansion interface{}
