// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	sealedsecretsv1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/apis/sealedsecrets/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SealedSecretLister helps list SealedSecrets.
// All objects returned here must be treated as read-only.
type SealedSecretLister interface {
	// List lists all SealedSecrets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sealedsecretsv1alpha1.SealedSecret, err error)
	// SealedSecrets returns an object that can list and get SealedSecrets.
	SealedSecrets(namespace string) SealedSecretNamespaceLister
	SealedSecretListerExpansion
}

// sealedSecretLister implements the SealedSecretLister interface.
type sealedSecretLister struct {
	listers.ResourceIndexer[*sealedsecretsv1alpha1.SealedSecret]
}

// NewSealedSecretLister returns a new SealedSecretLister.
func NewSealedSecretLister(indexer cache.Indexer) SealedSecretLister {
	return &sealedSecretLister{listers.New[*sealedsecretsv1alpha1.SealedSecret](indexer, sealedsecretsv1alpha1.Resource("sealedsecret"))}
}

// SealedSecrets returns an object that can list and get SealedSecrets.
func (s *sealedSecretLister) SealedSecrets(namespace string) SealedSecretNamespaceLister {
	return sealedSecretNamespaceLister{listers.NewNamespaced[*sealedsecretsv1alpha1.SealedSecret](s.ResourceIndexer, namespace)}
}

// SealedSecretNamespaceLister helps list and get SealedSecrets.
// All objects returned here must be treated as read-only.
type SealedSecretNamespaceLister interface {
	// List lists all SealedSecrets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sealedsecretsv1alpha1.SealedSecret, err error)
	// Get retrieves the SealedSecret from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*sealedsecretsv1alpha1.SealedSecret, error)
	SealedSecretNamespaceListerExpansion
}

// sealedSecretNamespaceLister implements the SealedSecretNamespaceLister
// interface.
type sealedSecretNamespaceLister struct {
	listers.ResourceIndexer[*sealedsecretsv1alpha1.SealedSecret]
}
