[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.98.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.98.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/*"
to = "/404/"
status = 404

# [[headers]]
#   for = "/*"
#   [headers.values]
#     # disabled to support docsearch until https://github.com/algolia/instantsearch.js/issues/2868 is fixed.
#     # Content-Security-Policy = "default-src 'self'; img-src *"
#     X-Content-Type-Options = "nosniff"
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
