FROM gcr.io/distroless/static@sha256:c6d5981545ce1406d33e61434c61e9452dad93ecd8397c41e89036ef977a88f4
LABEL maintainer="Marko Mikulicic <mkmik@vmware.com>"
COPY controller /usr/local/bin/

EXPOSE 8080
ENTRYPOINT ["controller"]
