// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	sealedsecretsv1alpha1 "github.com/bitnami-labs/sealed-secrets/pkg/apis/sealedsecrets/v1alpha1"
	scheme "github.com/bitnami-labs/sealed-secrets/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SealedSecretsGetter has a method to return a SealedSecretInterface.
// A group's client should implement this interface.
type SealedSecretsGetter interface {
	SealedSecrets(namespace string) SealedSecretInterface
}

// SealedSecretInterface has methods to work with SealedSecret resources.
type SealedSecretInterface interface {
	Create(ctx context.Context, sealedSecret *sealedsecretsv1alpha1.SealedSecret, opts v1.CreateOptions) (*sealedsecretsv1alpha1.SealedSecret, error)
	Update(ctx context.Context, sealedSecret *sealedsecretsv1alpha1.SealedSecret, opts v1.UpdateOptions) (*sealedsecretsv1alpha1.SealedSecret, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sealedSecret *sealedsecretsv1alpha1.SealedSecret, opts v1.UpdateOptions) (*sealedsecretsv1alpha1.SealedSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*sealedsecretsv1alpha1.SealedSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*sealedsecretsv1alpha1.SealedSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sealedsecretsv1alpha1.SealedSecret, err error)
	SealedSecretExpansion
}

// sealedSecrets implements SealedSecretInterface
type sealedSecrets struct {
	*gentype.ClientWithList[*sealedsecretsv1alpha1.SealedSecret, *sealedsecretsv1alpha1.SealedSecretList]
}

// newSealedSecrets returns a SealedSecrets
func newSealedSecrets(c *BitnamiV1alpha1Client, namespace string) *sealedSecrets {
	return &sealedSecrets{
		gentype.NewClientWithList[*sealedsecretsv1alpha1.SealedSecret, *sealedsecretsv1alpha1.SealedSecretList](
			"sealedsecrets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *sealedsecretsv1alpha1.SealedSecret { return &sealedsecretsv1alpha1.SealedSecret{} },
			func() *sealedsecretsv1alpha1.SealedSecretList { return &sealedsecretsv1alpha1.SealedSecretList{} },
		),
	}
}
